# The simple configuration file with all available settings.

[Monitor]
addr = "127.0.0.1"
port = "4200"


[Hub]
    [Hub.port7]
        port = "com7"
        type = "gsm"
        baudrate = "9600"
        parity = "N"
        stop = "1"
        size = "8"
        timeout = "5" #sec
